### ISSUE TITLE
error: (-215) ssize.area() > 0 in function resize

### ISSUE THREAD

**Issue by xiongdemao** [Huangying-Zhan/Depth-VO-Feat#4]
**Visual Odometry**
To generate the odometry predictions (relative camera motions), run the following script.
```
python ./tools/evaluation_tools.py --func generate_odom_result --model models/trained_models/odometry_split/Temporal.caffemodel --odom_net_def ./experiments/networks/odometry_deploy.prototxt --odom_result_dir ./result/odom_result
```
```
I0410 19:00:23.287318  7460 net.cpp:744] Ignoring source layer silence_train
Getting predictions... Sequence:  0  /  10
OpenCV Error: Assertion failed (ssize.area() > 0) in resize, file /home/travis/miniconda/conda-bld/conda_1486587066442/work/opencv-3.1.0/modules/imgproc/src/imgwarp.cpp, line 3229
Traceback (most recent call last):
  File "../../caffe-master/tools/evaluation_tools.py", line 648, in <module>
    pred_poses = generator.getPredPoses()
  File "../../caffe-master/tools/evaluation_tools.py", line 155, in getPredPoses
    img1 = self.getImage(img1_path)
  File "../../caffe-master/tools/evaluation_tools.py", line 125, in getImage
    img = cv2.resize(img, (self.image_width, self.image_height))
cv2.error: /home/travis/miniconda/conda-bld/conda_1486587066442/work/opencv-3.1.0/modules/imgproc/src/imgwarp.cpp:3229: error: (-215) ssize.area() > 0 in function resize

```

**Comment by Huangying-Zhan** [comment]
@xiongdemao could you check whether the img path is correct or not? if the path is incorrect, the img might be null and report an error while resizing.
Could you add a line after line 123 to check whether the img is read successfully?
`assert img!=None, "Image reading error. Check whether your image path is correct or not."`

If this is the case, please double check your image path.

**Comment by xiongdemao** [comment]
HI!I check file "evaluation_tools.py" again ,but there isn't " img_path" in the class " kittiPredOdom():"
```
class kittiPredOdom():
	def __init__(self):
		model_def = args.odom_net_def
		caffe_model = args.model
		self.odom_net = caffe.Net(model_def, caffe_model, caffe.TEST)
		self.image_width = self.odom_net.blobs['imgs'].data.shape[3]
		self.image_height = self.odom_net.blobs['imgs'].data.shape[2]

		self.result_path = args.odom_result_dir

		self.eval_seqs = ["00", "01", "02", "04", "05", "06", "07", "08", "09", "10"]
		self.eval_seqs_start_end = {
									"00": [0, 4540], 
									"01": [0, 1100], 
									"02": [0, 4660], 
									"04": [0, 270], 
									"05": [0, 2760],
									"06": [0, 1100], 
									"07": [0, 1100], 
									"08": [1100, 5170], 
									"09": [0, 1590], 
									"10": [0, 1200]
									}

		self.eval_seqs_path		 = {
									"00": "residential/2011_10_03_drive_0027",
									"01": "road/2011_10_03_drive_0042",
									"02": "residential/2011_10_03_drive_0034", 
									"04": "road/2011_09_30_drive_0016",
									"05": "residential/2011_09_30_drive_0018",
									"06": "residential/2011_09_30_drive_0020", 
									"07": "residential/2011_09_30_drive_0027",
									"08": "residential/2011_09_30_drive_0028", 
									"09": "residential/2011_09_30_drive_0033", 
									"10": "residential/2011_09_30_drive_0034"
									}


	def getImage(self, img_path): 
		# ----------------------------------------------------------------------
		# Get and preprocess image
		# ----------------------------------------------------------------------
		img = cv2.imread(img_path)
                assert img == None, "Image reading error. Check whether your image path is correct or not."
		# img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
		img = cv2.resize(img, (self.image_width, self.image_height))
		img = img.transpose((2,0,1))
		img = img.astype(np.float32)
		img[0] -= 104
		img[1] -= 117
		img[2] -= 123
		return img
```

**Comment by xiongdemao** [comment]
I find the reason,thank you !!!

**Comment by liruixl** [comment]
@xiongdemao Hello, can you tell me what is the reason? I also meet it. Thanks! memedaa

**Comment by Huangying-Zhan** [comment]
@liruixl  I think you can try to print the path of the image. Most likely the path is incorrect
